# 定义ClusterIP类型的Service（与pod及lease相同命名空间）
apiVersion: v1
kind: Service
metadata:
  name: meta-cluster-ip
  namespace: meta-service
spec:
  type: ClusterIP
  selector:
    app: meta-service
    role: master  # 仅选择主meta
  ports:
    - port: 18080        # Service暴露的端口（ClusterIP:18080）
      targetPort: 5000   # 后端Pod实际监听的端口，与meta配置文件中的ock.mmc.meta_service_url端口号保持一致
      protocol: TCP      # 显式指定TCP协议